# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e394a11988a6274b77d799019a076020bc67cb37ba9de57182d381e92eec67b3fb8e26148b1c77cd4a55a481e3bed7e21607005bd5975a96219ce028686e96e

test:
  secret_key_base: ddfbb49a4e226f1e3da3ba162350e93af2d148fa7eee26c6c91575b7e80dc4093de2f9edb728acd540eb1db2123a532ce89e855b38de852936944b8d6baea115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
